package com.nextfaze.devfun.reference

import com.nextfaze.devfun.DeveloperAnnotation

/**
 * Annotated elements will be recorded by DevFun for later retrieval via `devFun.developerReferences<DeveloperReference>()`.
 *
 * In general this is not used much beyond testing.
 *
 * Typically usage of this type is via your own custom annotations with [DeveloperAnnotation] à la [DeveloperLogger].
 *
 * @see DeveloperAnnotation
 * @see Dagger2Component
 * @see DeveloperLogger
 */
@Retention(AnnotationRetention.SOURCE)
@DeveloperAnnotation(developerReference = true)
annotation class DeveloperReference

/**
 * Properties interface for @[DeveloperReference].
 *
 * TODO: This interface should be generated by DevFun at compile time, but as the annotations are in a separate module to the compiler
 * that itself depends on the annotations module, it is non-trivial to run the DevFun processor upon it (module dependencies become cyclic).
 */
@Suppress("unused")
interface DeveloperReferenceProperties
