import org.gradle.api.DefaultTask
import org.gradle.api.Project
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.TaskAction
import org.gradle.kotlin.dsl.*
import java.io.File

fun Project.createVersionFile(pkg: String = "com.nextfaze.${name.replace("-", ".")}") {
    val version = version.toString()

    val outputDir = file("$buildDir/generated/source/devfun/main")
    val file = File(outputDir, "${pkg.replace(".", "/")}/version.kt")

    val task = tasks.create<CreateVersionFileTask>("createVersionFile") {
        versionName = version
        filePackage = pkg
        versionFile = file
    }

    tasks.getByName("compileKotlin").dependsOn(task)
    mainSrcDirs(outputDir)
}

open class CreateVersionFileTask : DefaultTask() {
    @get:Input
    lateinit var versionName: String

    @get:Input
    lateinit var filePackage: String

    @get:OutputFile
    lateinit var versionFile: File

    @TaskAction
    fun createVersionFile() {
        versionFile.writeText(
            """/** Generated by task - do not modify directly. */
package $filePackage

internal const val versionName = "$versionName"
"""
        )
    }
}
